language: node_js
node_js:
- '4'
env:
  global:
    secure: Dz2SXWTVO/O+D2e+u11jSM+Ne877gV9FSid+1vyTSQB8fK6yCFBXyc/zPSquF//6ZO/xUNCB/KObwJAcA2Oh56qAHaDX4R+GsjOMF5s41igw4Qcd5BROh0pszL/Mv9CLwEYepPxCJ8kPe/P4FPwV8xAtPO/Vl8RNQ2U3Uy1mgFQ2Tafp8ArgPnb9Xwy5DcqcHC8jsgYGojX8E2jM1SrZKJImlpxEkiBbrVB6K3nSCO49BbWz18AETl7tGZX7/dcMyIQWIwIq7IOAy1xgJl8MXn/B7wXdyGRjuyMKAs39sh3Gh4iikpX9uCPwy4x5HV3kGUSJI46zZhHD6axsN/7bWtGoG+LxCVW6pkrlFQm0oEJ9rWaMvjf5zGtN9c1G6WL0WWEXRmgcdzqLEICrt/xjhmnfhMkVb/bSTDJDYjmnPntXdNEe+ut4XQ+njw71upWTgMaKrAjjolnSiY3G2Cj1Hc4nd72LKeX3mBO0Ls3/aBtvHPOhUUEpKU/FqSrTXxtg73/YDnREqFg/9B36yF27c+duz+WWN+V2nxnmNgqhRDaf/abB7uKVSLsrpbEjqEMlBZ9zLttGNRYSNJaB8WrGf7oMx6YaAq5qxF5mHjrijosKVPF+6yzuDM0UhgvlzuhoPFaRhu4GUk2AiV9lZTFsY8eTOHXvDp9U1gI6H9CZJJ0=
after_success:
- scripts/travis-ci_auto-publish.sh
